from __future__ import annotations


STANDARD_COLUMNS = [
    "source_file",
    "source_type",
    "page",
    "sheet",
    "row_id",
    "table_id",
    "row_index_in_table",
    "section_name",
    "indicator",
    "commodity",
    "region",
    "route",
    "date",
    "value",
    "unit",
    "currency",
    "evidence_text",
    "bbox",
    "extraction_method",
    "extraction_level",
    "text_layer_quality",
    "text_layer_warning",
    "confidence",
]

ALLOWED_UNITS = {
    "kg",
    "ton",
    "piece",
    "RUB/ton",
    "USD/ton",
    "EUR/ton",
    "thousand_tons",
    "percent",
    "RUB/kg",
    "NOK/kg",
    "EUR/kg",
}

ALLOWED_CURRENCIES = {
    "RUB",
    "USD",
    "EUR",
}

UNIT_MAP = {
    "kg": "kg",
    "kgs": "kg",
    "kilogram": "kg",
    "kilograms": "kg",
    "t": "ton",
    "tn": "ton",
    "ton": "ton",
    "tons": "ton",
    "tonne": "ton",
    "tonnes": "ton",
    "mt": "ton",
    "pc": "piece",
    "pcs": "piece",
    "piece": "piece",
    "pieces": "piece",
    "unit": "piece",
    "units": "piece",
    "rub/ton": "RUB/ton",
    "rub/t": "RUB/ton",
    "rub per ton": "RUB/ton",
    "rur/ton": "RUB/ton",
    "rur/t": "RUB/ton",
    "usd/ton": "USD/ton",
    "usd/t": "USD/ton",
    "usd per ton": "USD/ton",
    "eur/ton": "EUR/ton",
    "eur/t": "EUR/ton",
    "eur per ton": "EUR/ton",
    "rub/kg": "RUB/kg",
    "rub per kg": "RUB/kg",
    "rur/kg": "RUB/kg",
    "nok/kg": "NOK/kg",
    "nok per kg": "NOK/kg",
    "eur/kg": "EUR/kg",
    "eur per kg": "EUR/kg",
    "thousand_tons": "thousand_tons",
    "thousand tons": "thousand_tons",
    "ths tons": "thousand_tons",
    "тыс тонн": "thousand_tons",
    "тыс. тонн": "thousand_tons",
    "тыс.тонн": "thousand_tons",
    "%": "percent",
    "percent": "percent",
    "percentage": "percent",
    "процент": "percent",
    "проценты": "percent",
}

CURRENCY_MAP = {
    "rub": "RUB",
    "rur": "RUB",
    "rouble": "RUB",
    "ruble": "RUB",
    "usd": "USD",
    "dollar": "USD",
    "dollars": "USD",
    "$": "USD",
    "eur": "EUR",
    "euro": "EUR",
    "euros": "EUR",
}
